import Head from 'next/head'
import Image from 'next/image'
import Main from './main'

export default function Home() {
  return (
    <div className="layout">
      <Head>
        <title>Watch</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="wrap">
        <Main />
      </div>
    </div>
  )
}
